apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${COLOR}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-demo
      version: ${COLOR}
  template:
    metadata:
      labels:
        app: blue-green-demo
        version: ${COLOR}
    spec:
      containers:
        - name: blue-green-demo
          image: sokilnatalka/ucu_test_kub:${GITHUB_SHA}
          ports:
            - containerPort: 5000
