apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-demo
      version: blue
  template:
    metadata:
      labels:
        app: blue-green-demo
        version: blue
    spec:
      containers:
        - name: blue-green-demo
          image: sokilnatalka/ucu_test_kub:blue
          ports:
            - containerPort: 5000
