apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-demo
      version: green
  template:
    metadata:
      labels:
        app: blue-green-demo
        version: green
    spec:
      containers:
        - name: blue-green-demo
          image: sokilnatalka/ucu_test_kub:green
          ports:
            - containerPort: 5000
