apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-demo
  namespace: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green-demo
  template:
    metadata:
      labels:
        app: blue-green-demo
    spec:
      containers:
        - name: blue-green-demo
          image: sokilnatalka/ucu_test_kub
          ports:
            - containerPort: 5000
